### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by NotAditya01** [NICK-FURY-6023/LyricLoom#1]
Node.js v17.8.0
• [ Api ]       => Successfully connected to MongoDB.
• [ Player ]    => Loaded: 8
• [ Node ]      => Loaded: 4
• [ Button ]    => Loaded: 6
• [ Commands ]  => Command Loaded: 41
• [ Client ]    => Loaded: 10
C:\Users\Aditya\Documents\LyricLoom-main\LyricLoom-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:136
    const invalidToken = new DiscordjsError(ErrorCodes.TokenInvalid);
                         ^

Error [TokenInvalid]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\Aditya\Documents\LyricLoom-main\LyricLoom-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:136:26)
    at Savaan.login (C:\Users\Aditya\Documents\LyricLoom-main\LyricLoom-main\node_modules\discord.js\src\client\Client.js:228:21)
    at Savaan.connect (C:\Users\Aditya\Documents\LyricLoom-main\LyricLoom-main\Src\Base\Client.js:141:15)
    at new Savaan (C:\Users\Aditya\Documents\LyricLoom-main\LyricLoom-main\Src\Base\Client.js:52:14)
    at Object.<anonymous> (C:\Users\Aditya\Documents\LyricLoom-main\LyricLoom-main\Src\Saavan.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'TokenInvalid'
}

even the token is correct still showing invaild

**Comment by NICK-FURY-6023** [comment]
did you paste your bot token properley ?

**Comment by NotAditya01** [comment]
Yes i pasted properly even tried multiple times

**Comment by NICK-FURY-6023** [comment]
ok join my server and share with me your error

**Comment by NICK-FURY-6023** [comment]
You are no response so we close this issue
